const shopItemsData = [
  {
    id: "ariete-coffee",
    name: "Ariete kaffebryggare",
    price: 500,
    desc: "Ariete kaffebryggare håller ditt nybryggda kaffe varmt längre. Välj själv när du vill att ditt kaffe ska vara klart och njut av den coola retrodesignen.",
    img: "/brands/ariete/coffee/ariete-vintage-kaffebryggare-(bla).png",
    colorTypes: [
      {
        id: "ariete-coffee-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/ariete/coffee/ariete-vintage-kaffebryggare-(bla).png",
      },
      {
        id: "ariete-coffee-blue",
        name: "blå",
        choice: "/beige.png",
        img: "/brands/ariete/coffee/ariete-vintage-kaffebryggare-(beige).png",
      },
      {
        id: "ariete-coffee-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/ariete/coffee/ariete-vintage-kaffebryggare-(gron).png",
      },
    ],
  },
  {
    id: "ariete-espresso",
    name: "Ariete espressomaskin",
    price: 1200,
    desc: "Skäm bort dig själv med ett riktigt gott kaffe. Ariete Vintage espressomaskin har manuell funktion, 0,9 liters vattentank, 15 bars tryck och mjölkskummare som låter dig njuta av goda espressos och cappuccinos varje dag.",
    img: "/brands/ariete/espresso/ariete-espressomaskin(bla).png",
    colorTypes: [
      {
        id: "ariete-espresso-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/ariete/espresso/ariete-espressomaskin(bla).png",
      },
      {
        id: "ariete-espresso-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/ariete/espresso/ariete-espressomaskin(gron).jpg",
      },
      {
        id: "ariete-espresso-beige",
        name: "Beige",
        choice: "/beige.png",
        img: "/brands/ariete/espresso/ariete-espressomaskin(beige).jpg",
      },
    ],
  },
  {
    id: "ariete-toaster",
    name: "Ariete brödrost",
    price: 450,
    desc: "Charmiga Ariete Vintage brödrost kommer med 6 effektlägen, Defrost, Re-heat, cancel-funktion, auto-eject samt löstagbar låda för smulor så du kan njuta av en riktigt god toast till frukosten.",
    img: "/brands/ariete/toaster/ariete-brodrost(bla).png",
    colorTypes: [
      {
        id: "ariete-toaster-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/ariete/toaster/ariete-brodrost(gron).jpg",
      },
      {
        id: "ariete-toaster-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/ariete/toaster/ariete-brodrost(bla).png",
      },
      {
        id: "ariete-toaster-beige",
        name: "Beige",
        choice: "/beige.png",
        img: "/brands/ariete/toaster/ariete-brodrost(beige).png",
      },
    ],
  },
  {
    id: "ariete-toaster-x4",
    name: "Ariete brödrost 4 skivor",
    price: 800,
    desc: "Med denna brödrost i vintage-design från Ariete kan du njuta av rostat bröd varje morgon. Brödrosten har plats till 4 skivor bröd och flera inställningar som gör att du rostar brödet precis efter dina preferenser. Den fina vintage-designen passar i det moderna, såväl som i det klassiska köket och rosten finns i olika färger, vilket gör att du kan välja den som passar bäst hos just dig.",
    img: "/brands/ariete/toaster-x4/ariete-brodrost-x4(gron).png",
    colorTypes: [
      {
        id: "ariete-toaster-x4-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/ariete/toaster-x4/ariete-brodrost-x4(gron).png",
      },
      {
        id: "ariete-toaster-x4-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/ariete/toaster-x4/ariete-brodrost-x4(bla).png",
      },
      {
        id: "ariete-toaster-x4-beige",
        img: "/brands/ariete/toaster-x4/ariete-brodrost-x4(beige).png",
      },
    ],
  },
  {
    id: "ariete-waterboiler",
    name: "Ariete vattenkokare",
    price: 450,
    desc: "Ariete Vintage vattenkokare ger dig hög kapacitet på 1,7 liter, snabb uppvärmning, automatisk avstängning och enkel rengöring så du enkelt kan förbereda ditt kaffe eller te för dig och dina vänner.",
    img: "/brands/ariete/water-boiler/ariete-vattenkokare(gron).png",
    colorTypes: [
      {
        id: "ariete-waterboiler-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/ariete/water-boiler/ariete-vattenkokare(bla).png",
      },
      {
        id: "ariete-waterboiler-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/ariete/water-boiler/ariete-vattenkokare(gron).png",
      },
      {
        id: "ariete-waterboiler-beige",
        name: "Beige",
        choice: "/beige.png",
        img: "/brands/ariete/water-boiler/ariete-vattenkokare(beige).png",
      },
    ],
  },
  {
    id: "smeg-blender",
    name: "Smeg blender",
    price: 2000,
    desc: "Kraftfull blender i 50-talsstil från italienska Smeg. Kannan rymmer 1,5 liter och tål temperaturer upp till 70ºC. Välj mellan fyra olika hastigheter och program för iskross och smoothie. Soft Start-funktionen gör att blendern startar långsamt och sedan ökar hastigheten vilket ger en säker blandning utan något onödigt skvätt.",
    img: "/brands/smeg/blender/smeg-blender(rosa).png",
    colorTypes: [
      {
        id: "smeg-blender-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/smeg/blender/smeg-blender(bla).png",
      },
      {
        id: "smeg-blender-pink",
        name: "Rosa",
        choice: "/pink.png",
        img: "/brands/smeg/blender/smeg-blender(rosa).png",
      },
      {
        id: "smeg-blender-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/smeg/blender/smeg-blender(gron).png",
      },
      {
        id: "smeg-blender-red",
        name: "Röd",
        choice: "/red.png",
        img: "/brands/smeg/blender/smeg-blender(rod).png",
      },
    ],
  },
  {
    id: "smeg-coffee",
    name: "Smeg kaffebryggare",
    price: 2000,
    desc: "Retroinspirerade 50's Style kaffebryggare från Smeg som blir en elegant touch i köket samtidigt som den ger dig ett riktigt gott kaffe! Kaffebryggare från Smeg kommer i många olika färgglada färger. Kaffemaskinen har en inbyggd smart timer där du kan du ställa in vilken tid du vill ha ditt nybryggda kaffe från Smeg. Ställ in timern och vakna till doften av nybryggt kaffe.",
    img: "/brands/smeg/coffee/smeg-kaffebryggare(pastellrosa).png",
    colorTypes: [
      {
        id: "smeg-coffee-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/smeg/coffee/smeg-kaffebryggare(pastellbla).png",
      },
      {
        id: "smeg-coffee-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/smeg/coffee/smeg-kaffebryggare(pastellgron).png",
      },
      {
        id: "smeg-coffee-pink",
        name: "Rosa",
        choice: "/pink.png",
        img: "/brands/smeg/coffee/smeg-kaffebryggare(pastellrosa).png",
      },
      {
        id: "smeg-coffee-red",
        name: "Röd",
        choice: "/red.png",
        img: "/brands/smeg/coffee/smeg-kaffebryggare(rod).png",
      },
    ],
  },
  {
    id: "smeg-espresso",
    name: "Smeg espressomaskin",
    price: 3000,
    desc: "Smeg espressomaskin har en elegant 50-talsinprirerad design. Rikligt snygg att ha framme på köksbänken. Förutom en snygg design gör Smeg espressomaskin också fantastiskt gott kaffe varje gång.",
    img: "/brands/smeg/espresso/smeg-manuell-espressomaskin(rosa).png",
    colorTypes: [
      {
        id: "smeg-espresso-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/smeg/espresso/smeg-manuell-espressomaskin(bla).png",
      },
      {
        id: "smeg-blender-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/smeg/espresso/smeg-manuell-espressomaskin(gron).png",
      },
      {
        id: "smeg-espresso-pink",
        name: "Rosa",
        choice: "/pink.png",
        img: "/brands/smeg/espresso/smeg-manuell-espressomaskin(rosa).png",
      },
      {
        id: "smeg-coffee-red",
        name: "Röd",
        choice: "/red.png",
        img: "/brands/smeg/espresso/smeg-manuell-espressomaskin(rod).png",
      },
    ],
  },
  {
    id: "smeg-kitchen-assistant",
    name: "Smeg köksmaskin",
    price: 4000,
    desc: "Stabil köksmaskin i 50-talsstil från italienska Smeg med modellnummer SMF02. Den har en stor skål på 4,8 liter tillverkad i polerad rostfritt stål. Den här köksmaskinen klarar allt från att vispa grädde till röra ihop bulldegar. Köksmaskinen med modellnummer SMF02 är en funktionell och snygg inredningsdetalj i ditt kök.",
    img: "/brands/smeg/kitchen-assistant/smeg-koksmaskin-bla.png",
    colorTypes: [
      {
        id: "smeg-kitchen-assistant-pink",
        name: "Rosa",
        choice: "/pink.png",
        img: "/brands/smeg/kitchen-assistant/smeg-koksmaskin-rosa.png",
      },
      {
        id: "smeg-kitchen-assistant-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/smeg/kitchen-assistant/smeg-koksmaskin-gron.png",
      },
      {
        id: "smeg-kitchen-assistant-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/smeg/kitchen-assistant/smeg-koksmaskin-gron.png",
      },
      {
        id: "smeg-kitchen-assistant-red",
        name: "Röd",
        choice: "/red.png",
        img: "/brands/smeg/kitchen-assistant/smeg-koksmaskin-rod.png",
      },
    ],
  },
  {
    id: "smeg-toaster-x4",
    name: "Smeg brödrost 4 skivor",
    price: 2000,
    desc: "Brödrost i 50-talsstil från italienska Smeg. Sex olika nivåer av rostningsgrad för perfekt bröd varje gång. Brödrosten har extra breda fack som rymmer två skivor på rad, samt löstagbar smuluppsamlare. En funktionell och snygg inredningsdetalj till ditt kök.",
    img: "/brands/smeg/toaster-x4/smeg-brodrost-x4-stal.png",
    colorTypes: [
      {
        id: "smeg-toaster-x4-pink",
        name: "Rosa",
        choice: "/pink.png",
        img: "/brands/smeg/toaster-x4/smeg-brodrost-x4-rosa.png",
      },
      {
        id: "smeg-toaster-x4-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/smeg/toaster-x4/smeg-brodrost-x4-pastellbla.png",
      },
      {
        id: "smeg-toaster-x4-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/smeg/toaster-x4/smeg-brodrost-x4-pastellgron.png",
      },
      {
        id: "smeg-toaster-x4-steel",
        name: "Stål",
        choice: "/steel.png",
        img: "/brands/smeg/toaster-x4/smeg-brodrost-x4-stal.png",
      },
      {
        id: "smeg-toaster-x4-red",
        name: "Röd",
        choice: "/red.png",
        img: "/brands/smeg/toaster-x4/smeg-brodrost-x4-rod.png",
      },
    ],
  },
  {
    id: "smeg-fridge-combined",
    name: "Smeg kylskåp kombinerat",
    price: 15000,
    desc: "Med Smeg 50 s Style kylskåp/frys kombiskåp FAB50RPG5 kan du addera stil och färg till ditt kök, samtidigt som du kan njuta av alla de teknologier du önskar från ett modernt kombiskåp. Det har justerbara hyllor, en låda för frukt och grönt, NoFrost-system och MultiAirFlow-kylning som tar väl hand om både färska och frysta matvaror.",
    img: "/brands/smeg/fridge/combined/smeg-kombinerad-kyl-&-frys(rod).png",
    colorTypes: [
      {
        id: "smeg-fridge-combined-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/smeg/fridge/combined/smeg-kombinerad-kyl-&-frys(bla).png",
      },
      {
        id: "smeg-fridge-combined-creme",
        name: "Creme",
        choice: "/beige.png",
        img: "/brands/smeg/fridge/combined/smeg-kombinerad-kyl-&-frys(creme).png",
      },
      {
        id: "smeg-fridge-combined-red",
        name: "Röd",
        choice: "/red.png",
        img: "/brands/smeg/fridge/combined/smeg-kombinerad-kyl-&-frys(rod).png",
      },
      {
        id: "smeg-fridge-combined-green",
        name: "RGrön",
        choice: "/green.png",
        img: "/brands/smeg/fridge/combined/smeg-kombinerad-kyl-&-frys(gron).png",
      },
    ],
  },
  {
    id: "smeg-fridge-green",
    name: "Smeg kylskåp",
    price: 10000,
    desc: "Smeg 50 s Style kylskåp med retrodesign tar inte mycket plats i köket men har ändå en rymlig 135 l-interiör och modern teknik som effektiv LED-belysning och ett enkelt avfrostningssystem. Denna modell är högergängad.",
    img: "/brands/smeg/fridge/small/smeg-fristaende-kylskap-gron.png",
    colorTypes: [
      {
        id: "smeg-fridge-pink",
        name: "Rosa",
        choice: "/pink.png",
        img: "/brands/smeg/fridge/small/smeg-fristaende-kylskap-rosa.png",
      },
      {
        id: "smeg-fridge-blue",
        name: "Blå",
        choice: "/blue.png",
        img: "/brands/smeg/fridge/small/smeg-fristaende-kylskap-bla.png",
      },
      {
        id: "smeg-fridge-green",
        name: "Grön",
        choice: "/green.png",
        img: "/brands/smeg/fridge/small/smeg-fristaende-kylskap-gron.png",
      },
      {
        img: "/brands/smeg/fridge/small/smeg-fristaende-kylskap-insida.png",
      },
    ],
  },
  {
    id: "smeg-fridge-special",
    name: "Smeg kylskåp Coca Cola",
    choice: "/red.png",
    price: 25000,
    desc: "Lägg till en uppfriskande accent till ditt kök med ett retro Smeg-kylskåp, som kommer i ett elegant Enjoy a Coke-tema. Detta fristående kylskåp erbjuder en 244-liters volym med ett Multiflow-system för pålitlig långtidsförvaring av dina matvaror.",
    img: "/brands/smeg/fridge/smeg-fristaende-kylskap-special.png",
  },
];
